### ISSUE TITLE
Needing early and mid-late 2005, early-mid 2006 and early 2013 players

### ISSUE THREAD

**Issue by SGR21gtb** [EricKrouss/2007-YouTube-Player-HTML5#1]
I'm desperate for these and I can't wait. Hopefully all features (**almost**) will be made along with info, share and like/dislike buttons on e2013 along with fake channel view count, sub button and description.

**Comment by EricKrouss** [comment]
Sorry I'm only doing the video player and not the full webpage. I welcome you to use the source code though :)
